packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@parcel/watcher": true
  "@prisma/engines": true
  "@swc/core": true
  "@uni-helper/unocss-preset-uni": true
  core-js: true
  esbuild: true
  less: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
  vue-demi: true
